# Generated by Django 4.0.6 on 2022-07-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=1)),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forca.words')),
            ],
        ),
        migrations.DeleteModel(
            name='Gues',
        ),
    ]
